#ifndef MED_QT_HPP
#define MED_QT_HPP

#define SCAN_COL_ADDRESS 0
#define SCAN_COL_TYPE 1
#define SCAN_COL_VALUE 2

#define ADDRESS_COL_DESCRIPTION 0
#define ADDRESS_COL_ADDRESS 1
#define ADDRESS_COL_TYPE 2
#define ADDRESS_COL_VALUE 3
#define ADDRESS_COL_LOCK 4

#endif
